// Generated by CoffeeScript 1.9.3
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/', function(req, res) {
    return res.render('about', {
      title: 'Rainbot | About'
    });
  });

  module.exports = router;

}).call(this);
