// Generated by CoffeeScript 1.9.3
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/', function(req, res) {
    return res.render('console', {
      title: 'Rainbot | Console'
    });
  }).post('/chat', function(req, res) {
    return res.render('partial/chat', {
      channels: bot.chans
    });
  }).post('/logs', function(req, res) {
    return res.render('partial/logs');
  });

  module.exports = router;

}).call(this);
