// Generated by CoffeeScript 1.9.3
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/', function(req, res) {
    return res.render('userguide', {
      title: 'Rainbot - User Guide'
    });
  });

  module.exports = router;

}).call(this);
