// Generated by CoffeeScript 1.9.3
(function() {
  var Console;

  Console = void 0;

  module.exports = function(Module, io) {
    Console = io.of('/console');
    return {
      message: {
        event: 'message',
        trigger: function(message) {
          return true;
        },
        action: function(respond, done) {
          Console.emit('message', {
            text: respond.text,
            from: respond.from,
            chan: respond.to
          });
          if (!console[respond.to]) {
            console[respond.to] = {};
            console[respond.to].messages = [];
          }
          console[respond.to].messages.push({
            message: {
              from: respond.from,
              text: respond.text
            }
          });
          if (console[respond.to].messages.length > 100) {
            console[respond.to].messages.shift();
          }
          return done();
        }
      }
    };
  };

}).call(this);
