// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(io) {
    var Console;
    Console = io.of('/console');
    Console.on('connection', function(socket) {
      return socket.on('backlog', function(data) {
        return Console.emit('backlog', [
          {
            message: {
              from: 'MistaWolf',
              text: 'This is a test message'
            }
          }, {
            action: {
              from: 'MistaWolf',
              text: 'This is a test action'
            }
          }
        ]);
      });
    });
    return io;
  };

}).call(this);
